### ISSUE TITLE
Overwritten information

### ISSUE THREAD

**Issue by druvus** [Emisam/genome_update#3]
Currently information in yaml file is overwritten if file exist and `-u` is not used. It would be better to give a warning that the file already exists.

**Comment by Emisam** [comment]
Designed to be carefully used. However, it's true that it's better not to overwrite existing files. Added it to my "to fix list".

**Comment by Emisam** [comment]
Fixed so it checks  all species if an isolate exist, instead of only in a specific one. This enables rearrangement within the yaml file.
